name: Instrumentation Test

on:
  workflow_call:

jobs:
  instrumentation-tests:
    name: Instrumentation Testing
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (since you're using Java 17)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Step 3: Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Step 4: Grant execute permission for the Gradle wrapper
      - name: Grant execute permission
        run: chmod +x gradlew

      # Step 5: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30            # Specify the API level
          target: default           # Use default target
          arch: x86_64              # Specify the architecture for the emulator
          profile: default          # Use default profile
          emulator-options: '-no-snapshot -no-audio -no-window'  # Emulator options
          disable-animations: true  # Disable animations for more stable tests

      # Step 6: Start the Android Emulator
      - name: Start emulator
        run: adb shell input keyevent 82 &
        shell: bash

      # Step 7: Wait for the Emulator to be ready
      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      # Step 8: Run connected Android tests
      - name: Execute Gradle Command - ./gradlew connectedAndroidTest
        run: ./gradlew connectedAndroidTest

      # Step 9: (Optional) Pull ADB logs in case of failures for debugging
      - name: Pull ADB logs
        run: adb logcat -d > logcat.txt

      # Step 10: (Optional) Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/
