name: Instrumentation Test

on:
  workflow_call:

jobs:
  connected-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Start Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: '-no-window -no-audio'
          script: ./gradlew connectedCheck

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run connected tests
        run: ./gradlew connectedCheck
