name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Execute Gradle Command - lint
        run: ./gradlew lint