name: On Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting
    uses: ./.github/workflows/lint.yml

  instrumentation:
    name: Instrumentation Testing
    uses: ./.github/workflows/instrumentation_test.yml

  assemble:
    name: Building debug APK
    needs: [lint, instrumentation]
    uses: ./.github/workflows/assemble_build.yml